name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run deployment script on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            cd /home/${{ secrets.VPS_USERNAME }}/simple-app-ci-cd/
            docker iamge pull ${{ secrets.DOCKER_USERNAME }}/simple-app-ci-cd:01 
            docker stop ct-simple-app
            docker rm ct-simple-app
            docker run -d --name ct-simple-app -p 9080:80 {{secrets.DOCKER_USERNAME}}/simple-app-ci-cd:01