name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2
        run: |
          aws ec2 describe-instances --filters "Name=tag:Name,Values=my-ec2-instance" --query 'Reservations[0].Instances[0].InstanceId'
          aws ssm send-command --instance-ids $(aws ec2 describe-instances --filters "Name=tag:Name,Values=my-ec2-instance" --query 'Reservations[0].Instances[0].InstanceId' --output text) --document-name "AWS-RunShellScript" --parameters '{"commands":["docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest", "docker stop myapp", "docker rm myapp", "docker run -d --name myapp -p 80:80 ${{ secrets.DOCKER_USERNAME }}/myapp:latest"]}'